// Fill out your copyright notice in the Description page of Project Settings.

#include "FPS/FPSPlayerCharacter.h"
#include "FPS/CharacterAttributeSet.h"
#include "FPS/PlayerAttributeSet.h"
#include "FPS/UI/PlayerHUD.h"
#include "FPS/UI/SkillTreeWidget.h"
#include "FPS/Components/WeaponSlotComponent.h"
#include "FPS/Components/SkillComponent.h"
#include "FPS/Components/InventoryComponent.h"
#include "FPS/Weapons/FPSWeapon.h"
#include "FPS/Items/WeaponItemData.h"
#include "FPS/Interfaces/Pickupable.h"
#include "AbilitySystemComponent.h"
#include "GameplayTagContainer.h"
#include "EnhancedInputComponent.h"
#include "EnhancedInputSubsystems.h"
#include "Blueprint/UserWidget.h"
#include "Kismet/KismetSystemLibrary.h"
#include "Abilities/GameplayAbility.h"
#include "GameFramework/CharacterMovementComponent.h"

AFPSPlayerCharacter::AFPSPlayerCharacter()
{
	// SkillComponent ìƒì„±
	SkillComponent = CreateDefaultSubobject<USkillComponent>(TEXT("SkillComponent"));

	// InventoryComponent ìƒì„±
	InventoryComponent = CreateDefaultSubobject<UInventoryComponent>(TEXT("InventoryComponent"));
}

void AFPSPlayerCharacter::BeginPlay()
{
	Super::BeginPlay();

	if (APlayerController* PC = Cast<APlayerController>(GetController()))
	{
		if (UEnhancedInputLocalPlayerSubsystem* Subsystem =
			ULocalPlayer::GetSubsystem<UEnhancedInputLocalPlayerSubsystem>(PC->GetLocalPlayer()))
		{
			if (DefaultMappingContext)
			{
				Subsystem->AddMappingContext(DefaultMappingContext, 0);
			}
			if (MouseLookMappingContext)
			{
				Subsystem->AddMappingContext(MouseLookMappingContext, 1);
			}
		}
	}

	// PlayerAttributeSet ì´ˆê¸°í™”
	if (AbilitySystemComponent)
	{
		const UPlayerAttributeSet* ExistingSet = AbilitySystemComponent->GetSet<UPlayerAttributeSet>();
		if (!ExistingSet)
		{
			UPlayerAttributeSet* NewSet = NewObject<UPlayerAttributeSet>(this);
			AbilitySystemComponent->AddAttributeSetSubobject(NewSet);
			PlayerAttributeSet = NewSet;
		}
		else
		{
			PlayerAttributeSet = const_cast<UPlayerAttributeSet*>(ExistingSet);
		}

		// SkillPoint ì†ì„± ë³€ê²½ì— ë°”ì¸ë”©
		AbilitySystemComponent->GetGameplayAttributeValueChangeDelegate(UPlayerAttributeSet::GetSkillPointAttribute()).AddUObject(this, &AFPSPlayerCharacter::OnSkillPointChanged);

		// MoveSpeedMultiplier ì†ì„± ë³€ê²½ì— ë°”ì¸ë”©
		AbilitySystemComponent->GetGameplayAttributeValueChangeDelegate(UPlayerAttributeSet::GetMoveSpeedMultiplierAttribute()).AddUObject(this, &AFPSPlayerCharacter::OnMoveSpeedMultiplierChanged);
	}

	// PlayerHUD ìƒì„±
	if (APlayerController* PC = Cast<APlayerController>(GetController()))
	{
		if (PlayerHUDClass)
		{
			PlayerHUDWidget = CreateWidget<UPlayerHUD>(PC, PlayerHUDClass);
			if (PlayerHUDWidget)
			{
				PlayerHUDWidget->AddToViewport();
				UE_LOG(LogTemp, Log, TEXT("PlayerHUD ìœ„ì ¯ ìƒì„± ì™„ë£Œ"));
			}
			else
			{
				UE_LOG(LogTemp, Error, TEXT("PlayerHUD ìƒì„± ì‹¤íŒ¨"));
			}
		}
	}
}

void AFPSPlayerCharacter::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);

	// í¬ë¡œìŠ¤í—¤ì–´ í™•ì‚° - ì´ë™ ì¤‘ì¼ ë•Œ
	if (WeaponSlotComponent)
	{
		AFPSWeapon* CurrentWeapon = WeaponSlotComponent->GetCurrentWeaponActor();
		if (CurrentWeapon && CurrentWeapon->GetWeaponItemData())
		{
			// ìºë¦­í„° ì´ë™ ì†ë„ ê°€ì ¸ì˜¤ê¸°
			FVector Velocity = GetVelocity();
			float Speed = Velocity.Size2D();

			// ì´ë™ ì†ë„ì— ë¹„ë¡€í•œ í™•ì‚° (0 ~ ìµœëŒ€ 10)
			float MovementSpread = FMath::Clamp(Speed / 100.0f, 0.0f, 10.0f);

			// HUDì— ì´ë™ í™•ì‚° ì„¤ì •
			UpdateCrosshairMovementSpread(MovementSpread);
		}
	}
}

void AFPSPlayerCharacter::SetupPlayerInputComponent(UInputComponent* PlayerInputComponent)
{
	Super::SetupPlayerInputComponent(PlayerInputComponent);

	// Enhanced Input Componentë¡œ ìºìŠ¤íŒ…
	if (UEnhancedInputComponent* EnhancedInputComponent = Cast<UEnhancedInputComponent>(PlayerInputComponent))
	{
		// ë°œì‚¬
		if (FireAction)
		{
			EnhancedInputComponent->BindAction(FireAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::FireAbilityPressed);
		}

		// ì´ë™
		if (MoveAction)
		{
			EnhancedInputComponent->BindAction(MoveAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::Move);
		}

		// ì‹œì  ë³€ê²½
		if (LookAction)
		{
			EnhancedInputComponent->BindAction(LookAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::Look);
		}

		// ì í”„
		if (JumpAction)
		{
			EnhancedInputComponent->BindAction(JumpAction, ETriggerEvent::Triggered, this, &ACharacter::Jump);
		}
		
		// ë¬´ê¸° ì „í™˜ ì…ë ¥
		if (SwitchWeaponAction)
		{
			EnhancedInputComponent->BindAction(SwitchWeaponAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::SwitchWeaponSlot);
		}

		if (PrimaryWeaponAction)
		{
			EnhancedInputComponent->BindAction(PrimaryWeaponAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::SwitchToPrimaryWeapon);
		}

		if (SecondaryWeaponAction)
		{
			EnhancedInputComponent->BindAction(SecondaryWeaponAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::SwitchToSecondaryWeapon);
		}

		// í”½ì—… ì…ë ¥
		if (PickupAction)
		{
			EnhancedInputComponent->BindAction(PickupAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::TryPickupItem);
		}

		// ë¦¬ë¡œë“œ ì…ë ¥
		if (ReloadAction)
		{
			EnhancedInputComponent->BindAction(ReloadAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::ReloadPressed);
		}

		// ìŠ¤í”„ë¦°íŠ¸ ì…ë ¥
		if (SprintAction)
		{
			EnhancedInputComponent->BindAction(SprintAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::Sprint);
		}

		// ìŠ¤í‚¬íŠ¸ë¦¬ UI í† ê¸€ ì…ë ¥ (Tí‚¤)
		if (ToggleSkillTreeAction)
		{
			EnhancedInputComponent->BindAction(ToggleSkillTreeAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::ToggleSkillTree);
		}

		// ì•¡í‹°ë¸Œ ìŠ¤í‚¬ ì‚¬ìš© ì…ë ¥ (Qí‚¤)
		if (ActiveSkillAction)
		{
			EnhancedInputComponent->BindAction(ActiveSkillAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::UseActiveSkill);
		}

		// í…ŒìŠ¤íŠ¸ìš© ìŠ¤í‚¬ ìŠµë“ ì…ë ¥ (Kí‚¤)
		if (TestSkillAction)
		{
			EnhancedInputComponent->BindAction(TestSkillAction, ETriggerEvent::Triggered, this, &AFPSPlayerCharacter::TestAcquireSkill);
		}
	}
}

void AFPSPlayerCharacter::OnHealthChanged(const FOnAttributeChangeData& Data)
{
	// HUD ì—…ë°ì´íŠ¸
	if (PlayerHUDWidget && AttributeSet)
	{
		PlayerHUDWidget->UpdateHealthBar(Data.NewValue, AttributeSet->GetMaxHealth());
	}

	// ë””ë²„ê·¸ ë©”ì‹œì§€ ì¶œë ¥
	if (GEngine)
	{
		GEngine->AddOnScreenDebugMessage(
			-1,
			5.f,
			FColor::Red,
			FString::Printf(TEXT("í˜„ì¬ ì²´ë ¥: %f"), Data.NewValue)
		);
	}

	// ì²´ë ¥ì´ 0 ì´í•˜ê°€ ë˜ë©´ ì‚¬ë§ ì²˜ë¦¬ (ë‹¨, ì´ë¯¸ ì£½ì€ ìƒíƒœê°€ ì•„ë‹ ë•Œë§Œ)
	if (Data.NewValue <= 0.0f && bIsAlive)
	{
		UE_LOG(LogTemp, Warning, TEXT("ì²´ë ¥ 0 ì´í•˜ - ì‚¬ë§ ì²˜ë¦¬ ì‹œì‘ (bIsAlive: %s)"), bIsAlive ? TEXT("true") : TEXT("false"));
		OnPlayerDeath();
	}
	else if (Data.NewValue <= 0.0f)
	{
		UE_LOG(LogTemp, Warning, TEXT("ì²´ë ¥ 0 ì´í•˜ì´ì§€ë§Œ ì´ë¯¸ ì£½ì€ ìƒíƒœ - ì‚¬ë§ ì²˜ë¦¬ ê±´ë„ˆëœ€"));
	}
}

void AFPSPlayerCharacter::OnStaminaChanged(const FOnAttributeChangeData& Data)
{
	// HUD ì—…ë°ì´íŠ¸
	if (PlayerHUDWidget && AttributeSet)
	{
		PlayerHUDWidget->UpdateStaminaBar(Data.NewValue, AttributeSet->GetMaxStamina());
	}

	UE_LOG(LogTemp, VeryVerbose, TEXT("ìŠ¤íƒœë¯¸ë‚˜ ë³€ê²½: %.1f / %.1f"), Data.NewValue, AttributeSet ? AttributeSet->GetMaxStamina() : 0.0f);

	// ìŠ¤íƒœë¯¸ë‚˜ê°€ 0 ì´í•˜ê°€ ë˜ë©´ Sprint Ability ìë™ ì¢…ë£Œ
	if (Data.NewValue <= 0.0f && AbilitySystemComponent)
	{
		FGameplayTag SprintTag = FGameplayTag::RequestGameplayTag(FName("Ability.Sprint"));
		TArray<FGameplayAbilitySpec*> ActiveAbilities;
		AbilitySystemComponent->GetActivatableGameplayAbilitySpecsByAllMatchingTags(
			FGameplayTagContainer(SprintTag),
			ActiveAbilities
		);

		for (FGameplayAbilitySpec* Spec : ActiveAbilities)
		{
			if (Spec && Spec->IsActive())
			{
				AbilitySystemComponent->CancelAbilityHandle(Spec->Handle);
				UE_LOG(LogTemp, Warning, TEXT("ìŠ¤íƒœë¯¸ë‚˜ ê³ ê°ˆ: Sprint Ability ìë™ ì¢…ë£Œ"));
			}
		}
	}
}

void AFPSPlayerCharacter::OnShieldChanged(const FOnAttributeChangeData& Data)
{
	// HUD ì—…ë°ì´íŠ¸
	if (PlayerHUDWidget && AttributeSet)
	{
		PlayerHUDWidget->UpdateShieldBar(Data.NewValue, AttributeSet->GetMaxShield());
	}

	UE_LOG(LogTemp, VeryVerbose, TEXT("ì‰´ë“œ ë³€ê²½: %.1f / %.1f"), Data.NewValue, AttributeSet ? AttributeSet->GetMaxShield() : 0.0f);
}

void AFPSPlayerCharacter::OnSkillPointChanged(const FOnAttributeChangeData& Data)
{
	// ìŠ¤í‚¬ í¬ì¸íŠ¸ ë³€ê²½ ì‹œ ë¡œê·¸ ì¶œë ¥ (ë‚˜ì¤‘ì— UI ì—…ë°ì´íŠ¸ ì¶”ê°€)
	UE_LOG(LogTemp, Log, TEXT("SkillPoint ë³€ê²½: %.0f"), Data.NewValue);

	// TODO: ìŠ¤í‚¬íŠ¸ë¦¬ UIê°€ ìˆë‹¤ë©´ ì—¬ê¸°ì„œ ì—…ë°ì´íŠ¸
}

void AFPSPlayerCharacter::OnMoveSpeedMultiplierChanged(const FOnAttributeChangeData& Data)
{
	// MoveSpeedMultiplier ë³€ê²½ ì‹œ CharacterMovement MaxWalkSpeed ì—…ë°ì´íŠ¸
	if (GetCharacterMovement())
	{
		const float BaseWalkSpeed = 600.0f;
		const float NewMaxWalkSpeed = BaseWalkSpeed * Data.NewValue;

		GetCharacterMovement()->MaxWalkSpeed = NewMaxWalkSpeed;

		UE_LOG(LogTemp, Warning, TEXT("ğŸƒ MoveSpeedMultiplier ë³€ê²½: %.2fx â†’ MaxWalkSpeed: %.0f"),
			Data.NewValue, NewMaxWalkSpeed);
	}
}

// === í”Œë ˆì´ì–´ ì „ìš© ì…ë ¥ í•¸ë“¤ëŸ¬ë“¤ ===

void AFPSPlayerCharacter::Move(const FInputActionValue& Value)
{
	// ì…ë ¥ì€ Vector2D í˜•íƒœ
	FVector2D MovementVector = Value.Get<FVector2D>();

	if (Controller != nullptr)
	{
		// ì´ë™ ì…ë ¥ ì¶”ê°€
		AddMovementInput(GetActorForwardVector(), MovementVector.Y);
		AddMovementInput(GetActorRightVector(), MovementVector.X);
	}
}

void AFPSPlayerCharacter::Look(const FInputActionValue& Value)
{
	// ì…ë ¥ì€ Vector2D í˜•íƒœ
	FVector2D LookAxisVector = Value.Get<FVector2D>();

	if (Controller != nullptr)
	{
		// ì»¨íŠ¸ë¡¤ëŸ¬ì— yaw ë° pitch ì…ë ¥ ì¶”ê°€
		AddControllerYawInput(LookAxisVector.X);
		AddControllerPitchInput(LookAxisVector.Y);
	}
}

void AFPSPlayerCharacter::FireAbilityPressed(const FInputActionValue& Value)
{
	const bool bPressed = Value.Get<bool>();
	if (bPressed)
	{
		// ìƒˆë¡œìš´ WeaponSlotComponent ì‹œìŠ¤í…œ ì‚¬ìš©
		if (WeaponSlotComponent)
		{
			if (AFPSWeapon* CurrentWeapon = WeaponSlotComponent->GetCurrentWeaponActor())
			{
				CurrentWeapon->StartFiring();
			}
		}
		// í•˜ìœ„ í˜¸í™˜ì„±ì„ ìœ„í•´ íƒœê·¸ ê¸°ë°˜ ì–´ë¹Œë¦¬í‹° í™œì„±í™”ë¡œ í´ë°±
		else if (AbilitySystemComponent)
		{
			bool bSuccess = AbilitySystemComponent->TryActivateAbilitiesByTag(
				FGameplayTagContainer(FGameplayTag::RequestGameplayTag(FName("Ability.Fire")))
			);

			if (!bSuccess)
			{
				UE_LOG(LogTemp, Warning, TEXT("FireAbilityPressed: ë°œì‚¬ ì–´ë¹Œë¦¬í‹° í™œì„±í™” ì‹¤íŒ¨"));
			}
		}
	}
	else
	{
		// ë²„íŠ¼ì„ ë–¼ë©´ ë°œì‚¬ ì¤‘ì§€
		if (WeaponSlotComponent)
		{
			if (AFPSWeapon* CurrentWeapon = WeaponSlotComponent->GetCurrentWeaponActor())
			{
				CurrentWeapon->StopFiring();
			}
		}
	}
}

void AFPSPlayerCharacter::SwitchWeaponSlot(const FInputActionValue& Value)
{
	if (WeaponSlotComponent)
	{
		WeaponSlotComponent->SwitchToNextSlot();
	}
}

void AFPSPlayerCharacter::SwitchToPrimaryWeapon(const FInputActionValue& Value)
{
	if (WeaponSlotComponent)
	{
		WeaponSlotComponent->SwitchToSlotByNumber(1); // 1 = Primary
	}
}

void AFPSPlayerCharacter::SwitchToSecondaryWeapon(const FInputActionValue& Value)
{
	if (WeaponSlotComponent)
	{
		WeaponSlotComponent->SwitchToSlotByNumber(2); // 2 = Secondary
	}
}

void AFPSPlayerCharacter::TryPickupItem(const FInputActionValue& Value)
{
	// Eí‚¤ê°€ ëˆŒë ¸ëŠ”ì§€ í™•ì¸
	const bool bPressed = Value.Get<bool>();
	if (!bPressed)
	{
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("Eí‚¤ í”½ì—… ì‹œë„"));

	// í”Œë ˆì´ì–´ ìœ„ì¹˜ì—ì„œ SphereTrace ìˆ˜í–‰
	FVector PlayerLocation = GetActorLocation();
	float PickupRange = 200.0f; // í”½ì—… ë²”ìœ„

	// ì˜¤ë¸Œì íŠ¸ íƒ€ì… í•„í„°
	TArray<TEnumAsByte<EObjectTypeQuery>> ObjectTypes;
	ObjectTypes.Add(UEngineTypes::ConvertToObjectType(ECC_WorldDynamic));

	// ì¶©ëŒ ë¬´ì‹œ ì•¡í„° ì„¤ì •
	TArray<AActor*> ActorsToIgnore;
	ActorsToIgnore.Add(this);

	// ì˜¤ë²„ë© ê²°ê³¼
	TArray<AActor*> OutActors;
	const bool bAny = UKismetSystemLibrary::SphereOverlapActors(
		GetWorld(),
		PlayerLocation,
		PickupRange,
		ObjectTypes,
		/*ClassFilter=*/AActor::StaticClass(),
		ActorsToIgnore,
		OutActors
	);

	if (!bAny)
	{
		UE_LOG(LogTemp, Log, TEXT("ì£¼ë³€ì— í”½ì—… ê°€ëŠ¥í•œ ì•„ì´í…œì´ ì—†ìŠµë‹ˆë‹¤"));
		return;
	}

	// ê°€ì¥ ê°€ê¹Œìš´ Pickupable ì•„ì´í…œ ê³ ë¥´ê¸° (+ ìƒíƒœ ì²´í¬)
	IPickupable* ClosestPickupable = nullptr;
	float ClosestDistance = FLT_MAX;

	for (AActor* OverlapActor : OutActors)
	{
		if (OverlapActor)
		{
			if (IPickupable* Pickupable = Cast<IPickupable>(OverlapActor))
			{
				// ë“œë¡­ëœ ìƒíƒœì¸ ì•„ì´í…œë§Œ ê³ ë ¤
				if (Pickupable->IsDropped())
				{
					float Distance = FVector::Dist(PlayerLocation, OverlapActor->GetActorLocation());
					if (Distance < ClosestDistance)
					{
						ClosestDistance = Distance;
						ClosestPickupable = Pickupable;
					}
				}
			}
		}
	}

	// ê°€ì¥ ê°€ê¹Œìš´ ì•„ì´í…œ í”½ì—… ì‹œë„
	if (ClosestPickupable)
	{
		UE_LOG(LogTemp, Log, TEXT("ê°€ì¥ ê°€ê¹Œìš´ ì•„ì´í…œ í”½ì—… ì‹œë„: %s"), *ClosestPickupable->GetPickupDisplayName());
		ClosestPickupable->OnPickedUp(this);
	}
	else
	{
		UE_LOG(LogTemp, Log, TEXT("í”½ì—… ê°€ëŠ¥í•œ ì•„ì´í…œì„ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤"));
	}
}

void AFPSPlayerCharacter::ReloadPressed(const FInputActionValue& Value)
{
	// Rí‚¤ê°€ ëˆŒë ¸ëŠ”ì§€ í™•ì¸
	const bool bPressed = Value.Get<bool>();
	if (!bPressed)
	{
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("Rí‚¤ ë¦¬ë¡œë“œ ì‹œë„"));

	// GameplayAbility_Reload í™œì„±í™”
	if (AbilitySystemComponent)
	{
		// ë¦¬ë¡œë“œ ì–´ë¹Œë¦¬í‹° í´ë˜ìŠ¤ë¡œ ì–´ë¹Œë¦¬í‹° í™œì„±í™” ì‹œë„
		// ì–´ë¹Œë¦¬í‹° í´ë˜ìŠ¤ëŠ” Blueprintì—ì„œ ì„¤ì •í•´ì•¼ í•¨
		bool bSuccess = AbilitySystemComponent->TryActivateAbilitiesByTag(FGameplayTagContainer(FGameplayTag::RequestGameplayTag(FName("Ability.Reload"))));

		if (!bSuccess)
		{
			UE_LOG(LogTemp, Warning, TEXT("ReloadPressed: ë¦¬ë¡œë“œ ì–´ë¹Œë¦¬í‹° í™œì„±í™” ì‹¤íŒ¨ (ì–´ë¹Œë¦¬í‹°ê°€ ì—†ê±°ë‚˜ ì¡°ê±´ ë¶ˆì¶©ì¡±)"));
		}
	}
	else
	{
		UE_LOG(LogTemp, Error, TEXT("ReloadPressed: AbilitySystemComponentê°€ nullì…ë‹ˆë‹¤"));
	}
}

void AFPSPlayerCharacter::Sprint(const FInputActionValue& Value)
{
	// Shift í‚¤ ìƒíƒœ í™•ì¸ (true = ëˆŒë¦¼, false = ë—Œ)
	const bool bIsSprinting = Value.Get<bool>();

	if (!AbilitySystemComponent)
	{
		return;
	}

	if (bIsSprinting)
	{
		// Shift ëˆŒë¦¼: Sprint Ability í™œì„±í™”
		UE_LOG(LogTemp, Log, TEXT("Shift í‚¤ ëˆŒë¦¼: Sprint ì‹œì‘ ì‹œë„"));
		bool bSuccess = AbilitySystemComponent->TryActivateAbilitiesByTag(
			FGameplayTagContainer(FGameplayTag::RequestGameplayTag(FName("Ability.Sprint")))
		);

		if (!bSuccess)
		{
			UE_LOG(LogTemp, Warning, TEXT("Sprint: ì–´ë¹Œë¦¬í‹° í™œì„±í™” ì‹¤íŒ¨ (ìŠ¤íƒœë¯¸ë‚˜ ë¶€ì¡± ë˜ëŠ” ì–´ë¹Œë¦¬í‹° ì—†ìŒ)"));
		}
	}
	else
	{
		// Shift ë—Œ: Sprint Ability ì¢…ë£Œ
		UE_LOG(LogTemp, Log, TEXT("Shift í‚¤ ë—Œ: Sprint ì¢…ë£Œ ì‹œë„"));

		// í™œì„±í™”ëœ Sprint Ability ì°¾ì•„ì„œ ì¢…ë£Œ
		FGameplayTag SprintTag = FGameplayTag::RequestGameplayTag(FName("Ability.Sprint"));
		TArray<FGameplayAbilitySpec*> ActiveAbilities;
		AbilitySystemComponent->GetActivatableGameplayAbilitySpecsByAllMatchingTags(
			FGameplayTagContainer(SprintTag),
			ActiveAbilities
		);

		for (FGameplayAbilitySpec* Spec : ActiveAbilities)
		{
			if (Spec && Spec->IsActive())
			{
				AbilitySystemComponent->CancelAbilityHandle(Spec->Handle);
				UE_LOG(LogTemp, Log, TEXT("Sprint Ability ì¢…ë£Œë¨"));
			}
		}
	}
}

// === IFPSWeaponHolder ì¸í„°í˜ì´ìŠ¤ ì˜¤ë²„ë¼ì´ë“œ (HUD ì—…ë°ì´íŠ¸) ===

void AFPSPlayerCharacter::UpdateWeaponHUD(int32 CurrentAmmo, int32 MagazineSize)
{
	if (!PlayerHUDWidget)
	{
		return;
	}

	// íƒ„ì•½ ì •ë³´ ì—…ë°ì´íŠ¸
	PlayerHUDWidget->UpdateAmmoDisplay(CurrentAmmo, MagazineSize);

	// í˜„ì¬ ë¬´ê¸° ì´ë¦„ë„ ì—…ë°ì´íŠ¸
	if (WeaponSlotComponent)
	{
		if (AFPSWeapon* CurrentWeapon = WeaponSlotComponent->GetCurrentWeaponActor())
		{
			if (UWeaponItemData* WeaponData = CurrentWeapon->GetWeaponItemData())
			{
				PlayerHUDWidget->UpdateWeaponName(WeaponData->GetItemName());
			}
		}
		else
		{
			PlayerHUDWidget->UpdateWeaponName("");
		}

		// ìŠ¬ë¡¯ ìƒíƒœë„ ì—…ë°ì´íŠ¸
		FString PrimaryWeaponName = "";
		FString SecondaryWeaponName = "";

		if (UWeaponItemData* PrimaryData = WeaponSlotComponent->GetWeaponInSlot(EWeaponSlot::Primary))
		{
			PrimaryWeaponName = PrimaryData->GetItemName();
		}

		if (UWeaponItemData* SecondaryData = WeaponSlotComponent->GetWeaponInSlot(EWeaponSlot::Secondary))
		{
			SecondaryWeaponName = SecondaryData->GetItemName();
		}

		int32 ActiveSlotNumber = 0;
		EWeaponSlot CurrentSlot = WeaponSlotComponent->GetActiveSlot();
		if (CurrentSlot == EWeaponSlot::Primary) ActiveSlotNumber = 1;
		else if (CurrentSlot == EWeaponSlot::Secondary) ActiveSlotNumber = 2;

		PlayerHUDWidget->UpdateWeaponSlots(PrimaryWeaponName, SecondaryWeaponName, ActiveSlotNumber);
	}

	UE_LOG(LogTemp, VeryVerbose, TEXT("WeaponHUD ì—…ë°ì´íŠ¸: %d/%d"), CurrentAmmo, MagazineSize);
}

void AFPSPlayerCharacter::UpdateCrosshairFiringSpread(float Spread)
{
	if (PlayerHUDWidget)
	{
		PlayerHUDWidget->SetCrosshairFiringSpread(Spread);
	}
}

void AFPSPlayerCharacter::UpdateCrosshairMovementSpread(float Spread)
{
	if (PlayerHUDWidget)
	{
		PlayerHUDWidget->SetCrosshairMovementSpread(Spread);
	}
}

void AFPSPlayerCharacter::OnWeaponActivated(AFPSWeapon* Weapon)
{
	if (!Weapon)
	{
		return;
	}

	// ì œê³µëœ ì• ë‹˜ ì¸ìŠ¤í„´ìŠ¤ í´ë˜ìŠ¤ ì„¤ì •
	if (TSubclassOf<UAnimInstance> FPAnimClass = Weapon->GetFirstPersonAnimInstanceClass())
	{
		if (FirstPersonMesh)
		{
			FirstPersonMesh->SetAnimInstanceClass(FPAnimClass);
		}
	}

	if (TSubclassOf<UAnimInstance> TPAnimClass = Weapon->GetThirdPersonAnimInstanceClass())
	{
		if (GetMesh())
		{
			GetMesh()->SetAnimInstanceClass(TPAnimClass);
		}
	}

	// HUD ì—…ë°ì´íŠ¸
	if (PlayerHUDWidget && Weapon->GetWeaponItemData())
	{
		float WeaponBaseSpread = Weapon->GetWeaponItemData()->CrosshairBaseSpread;
		PlayerHUDWidget->SetBaseCrosshairSpread(WeaponBaseSpread);
	}
}

void AFPSPlayerCharacter::OnWeaponDeactivated(AFPSWeapon* Weapon)
{
	Super::OnWeaponDeactivated(Weapon);

	if (WeaponSlotComponent)
	{
		if (AFPSWeapon* CurrentWeapon = WeaponSlotComponent->GetCurrentWeaponActor())
		{
			CurrentWeapon->StopFiring();
		}
	}

	// ë¬´ê¸° ê´€ë ¨ ëª¨ë“  í™œì„±í™”ëœ ì–´ë¹Œë¦¬í‹° ì·¨ì†Œ
	if (AbilitySystemComponent)
	{
		// ë°œì‚¬ ë° ë¦¬ë¡œë“œ ì–´ë¹Œë¦¬í‹° ê°•ì œ ì·¨ì†Œ
		FGameplayTagContainer AbilitiesToCancel;
		AbilitiesToCancel.AddTag(FGameplayTag::RequestGameplayTag(FName("Ability.Fire")));
		AbilitiesToCancel.AddTag(FGameplayTag::RequestGameplayTag(FName("Ability.Reload")));

		AbilitySystemComponent->CancelAbilities(&AbilitiesToCancel);

		UE_LOG(LogTemp, Warning, TEXT("OnWeaponDeactivated: ë¬´ê¸° ê´€ë ¨ ì–´ë¹Œë¦¬í‹°ë“¤ ì·¨ì†Œ"));
	}

	// ê¸°ë³¸ ì• ë‹˜ ì¸ìŠ¤í„´ìŠ¤ í´ë˜ìŠ¤ë¡œ ë³µì›
	if (DefaultFirstPersonAnimClass && FirstPersonMesh)
	{
		FirstPersonMesh->SetAnimInstanceClass(DefaultFirstPersonAnimClass);
		UE_LOG(LogTemp, Log, TEXT("1ì¸ì¹­ ì• ë‹ˆë©”ì´ì…˜ì„ ê¸°ë³¸ê°’ìœ¼ë¡œ ë³µì›"));
	}

	if (DefaultThirdPersonAnimClass && GetMesh())
	{
		GetMesh()->SetAnimInstanceClass(DefaultThirdPersonAnimClass);
		UE_LOG(LogTemp, Log, TEXT("3ì¸ì¹­ ì• ë‹ˆë©”ì´ì…˜ì„ ê¸°ë³¸ê°’ìœ¼ë¡œ ë³µì›"));
	}

	// ë¬´ê¸° í•´ì œ ì‹œ BaseCrosshairSpreadë¥¼ 0ìœ¼ë¡œ ì´ˆê¸°í™”
	if (PlayerHUDWidget)
	{
		PlayerHUDWidget->SetBaseCrosshairSpread(0.0f);
	}
}

void AFPSPlayerCharacter::TestAcquireSkill(const FInputActionValue& Value)
{
	if (!SkillComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("TestAcquireSkill: SkillComponentê°€ ì—†ìŠµë‹ˆë‹¤."));
		return;
	}

	// í…ŒìŠ¤íŠ¸ìš© ìŠ¤í‚¬ ID (Blueprint DataAsset ìƒì„± í›„ ì„¤ì •)
	FGameplayTag TestSkillTag = FGameplayTag::RequestGameplayTag(FName("Skill.Common.MaxHealth"));

	UE_LOG(LogTemp, Log, TEXT("TestAcquireSkill: ìŠ¤í‚¬ ìŠµë“ ì‹œë„ - %s"), *TestSkillTag.ToString());

	// ìŠ¤í‚¬ ìŠµë“ ì‹œë„
	ESkillAcquireResult Result = SkillComponent->TryAcquireSkill(TestSkillTag);

	// ê²°ê³¼ ë¡œê·¸
	switch (Result)
	{
	case ESkillAcquireResult::Success:
		UE_LOG(LogTemp, Log, TEXT("TestAcquireSkill: ìŠ¤í‚¬ ìŠµë“ ì„±ê³µ!"));
		break;
	case ESkillAcquireResult::AlreadyAcquired:
		UE_LOG(LogTemp, Warning, TEXT("TestAcquireSkill: ì´ë¯¸ ìŠµë“í•œ ìŠ¤í‚¬ì…ë‹ˆë‹¤."));
		break;
	case ESkillAcquireResult::InsufficientPoints:
		UE_LOG(LogTemp, Warning, TEXT("TestAcquireSkill: ìŠ¤í‚¬ í¬ì¸íŠ¸ê°€ ë¶€ì¡±í•©ë‹ˆë‹¤."));
		break;
	case ESkillAcquireResult::PrerequisiteNotMet:
		UE_LOG(LogTemp, Warning, TEXT("TestAcquireSkill: ì„ í–‰ ìŠ¤í‚¬ì´ í•„ìš”í•©ë‹ˆë‹¤."));
		break;
	case ESkillAcquireResult::InvalidSkill:
		UE_LOG(LogTemp, Warning, TEXT("TestAcquireSkill: ìœ íš¨í•˜ì§€ ì•Šì€ ìŠ¤í‚¬ IDì…ë‹ˆë‹¤. SkillDataArrayì— í•´ë‹¹ ìŠ¤í‚¬ì„ ì¶”ê°€í•˜ì„¸ìš”."));
		break;
	}
}

void AFPSPlayerCharacter::UseActiveSkill(const FInputActionValue& Value)
{
	if (!AbilitySystemComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("UseActiveSkill: AbilitySystemComponentê°€ ì—†ìŒ"));
		return;
	}

	// í˜„ì¬ ë¶€ì—¬ëœ Ability ëª©ë¡ ì¶œë ¥ (ë””ë²„ê¹…)
	TArray<FGameplayAbilitySpec>& ActivatableAbilities = AbilitySystemComponent->GetActivatableAbilities();
	UE_LOG(LogTemp, Log, TEXT("=== í˜„ì¬ ë¶€ì—¬ëœ Ability ëª©ë¡ (%dê°œ) ==="), ActivatableAbilities.Num());
	for (const FGameplayAbilitySpec& Spec : ActivatableAbilities)
	{
		if (Spec.Ability)
		{
			// GetAssetTags()ë¡œ íƒœê·¸ ê°€ì ¸ì˜¤ê¸°
			const FGameplayTagContainer& SpecAbilityTags = Spec.Ability->GetAssetTags();
			FString TagsString = SpecAbilityTags.ToStringSimple();
			UE_LOG(LogTemp, Log, TEXT("  - %s (Tags: %s)"), *Spec.Ability->GetName(), *TagsString);
		}
	}

	// SkillComponentì—ì„œ ìŠµë“í•œ ì•¡í‹°ë¸Œ ìŠ¤í‚¬ íƒœê·¸ ê°€ì ¸ì˜¤ê¸°
	if (!SkillComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("UseActiveSkill: SkillComponentê°€ ì—†ìŒ"));
		return;
	}

	FGameplayTag ActiveSkillTag = SkillComponent->GetActiveSkillAbilityTag();
	if (!ActiveSkillTag.IsValid())
	{
		UE_LOG(LogTemp, Warning, TEXT("UseActiveSkill: ìŠµë“í•œ ì•¡í‹°ë¸Œ ìŠ¤í‚¬ì´ ì—†ìŒ"));
		return;
	}

	UE_LOG(LogTemp, Log, TEXT("ì°¾ìœ¼ë ¤ëŠ” íƒœê·¸: %s"), *ActiveSkillTag.ToString());

	// ì•¡í‹°ë¸Œ ìŠ¤í‚¬ í™œì„±í™”
	FGameplayTagContainer AbilityTags;
	AbilityTags.AddTag(ActiveSkillTag);

	bool bActivated = AbilitySystemComponent->TryActivateAbilitiesByTag(AbilityTags);
	if (!bActivated)
	{
		UE_LOG(LogTemp, Warning, TEXT("UseActiveSkill: ì•¡í‹°ë¸Œ ìŠ¤í‚¬ì´ ì—†ê±°ë‚˜ ì‚¬ìš©í•  ìˆ˜ ì—†ìŒ (ì¿¨ë‹¤ìš´ ì¤‘?)"));
	}
	else
	{
		UE_LOG(LogTemp, Log, TEXT("UseActiveSkill: ì•¡í‹°ë¸Œ ìŠ¤í‚¬ í™œì„±í™” ì„±ê³µ!"));
	}
}

void AFPSPlayerCharacter::ToggleSkillTree(const FInputActionValue& Value)
{
	// PlayerController ì²´í¬ (AIëŠ” UI ì‚¬ìš© ì•ˆí•¨)
	APlayerController* PC = Cast<APlayerController>(GetController());
	if (!PC)
	{
		return;
	}

	// ìŠ¤í‚¬íŠ¸ë¦¬ UIê°€ ì´ë¯¸ ì—´ë ¤ ìˆìœ¼ë©´ ë‹«ê¸°
	if (SkillTreeWidget && SkillTreeWidget->IsInViewport())
	{
		SkillTreeWidget->RemoveFromParent();
		SkillTreeWidget = nullptr;

		// ë§ˆìš°ìŠ¤ ì»¤ì„œ ìˆ¨ê¸°ê¸°, ê²Œì„ ëª¨ë“œë¡œ ë³µê·€
		PC->SetShowMouseCursor(false);
		PC->SetInputMode(FInputModeGameOnly());

		UE_LOG(LogTemp, Log, TEXT("SkillTree UI ë‹«ê¸°"));
		return;
	}

	// ìŠ¤í‚¬íŠ¸ë¦¬ UI ì—´ê¸°
	if (!SkillComponent)
	{
		UE_LOG(LogTemp, Warning, TEXT("ToggleSkillTree: SkillComponentê°€ ì—†ìŠµë‹ˆë‹¤."));
		return;
	}

	if (!SkillTreeWidgetClass)
	{
		UE_LOG(LogTemp, Warning, TEXT("ToggleSkillTree: SkillTreeWidgetClassê°€ ì„¤ì •ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤."));
		return;
	}

	// ìœ„ì ¯ ìƒì„±
	SkillTreeWidget = CreateWidget<USkillTreeWidget>(PC, SkillTreeWidgetClass);
	if (SkillTreeWidget)
	{
		// SkillComponent ì—°ë™
		SkillTreeWidget->InitializeSkillTree(SkillComponent);

		// ìŠ¤í‚¬ í¬ì¸íŠ¸ í‘œì‹œ
		if (PlayerAttributeSet)
		{
			SkillTreeWidget->UpdateSkillPointDisplay(PlayerAttributeSet->GetSkillPoint());
		}

		// í™”ë©´ì— ì¶”ê°€
		SkillTreeWidget->AddToViewport();

		// ë§ˆìš°ìŠ¤ ì»¤ì„œ í‘œì‹œ, UI ëª¨ë“œë¡œ ì „í™˜
		PC->SetShowMouseCursor(true);
		FInputModeGameAndUI InputMode;
		InputMode.SetWidgetToFocus(SkillTreeWidget->TakeWidget());
		PC->SetInputMode(InputMode);

		UE_LOG(LogTemp, Log, TEXT("SkillTree UI ì—´ê¸°"));
	}
}
